services:
  # Backend API Service
  - type: web
    name: lullaibot-edu-api
    env: node
    rootDir: src/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false # This will be set manually in Render dashboard
      - key: FRONTEND_URL
        fromService:
          name: lullaibot-edu-frontend
          type: web
          property: host
          envVarPrefix: "https://"

  # Frontend Static Site
  - type: web
    name: lullaibot-edu-frontend
    env: static
    rootDir: .
    buildCommand: npm install && VITE_API_URL=https://lullaibot-edu-api.onrender.com/api npm run build
    staticPublishPath: ./dist
    # Add routes for SPA
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: "https://lullaibot-edu-api.onrender.com/api" 